### ISSUE TITLE
Remove usage of Lizard API v2

### ISSUE THREAD

**Issue by caspervdw** [nens/rain_report#27]
Ready to deploy to production:
1.6.51
When something goes wrong:
Revert prod back to v1.6.29
I verified that the config.json was not changed in the meanwhile.

Also closed duplicate:
https://github.com/nens/lizard-client/issues/1116
======================================

See https://github.com/nens/lizard-nxt/issues/4412

API endpoints used: wms, raster-aggregates

I see multiple portals using this tool: hhnk, waternet, vitens, wdodelta, demo, saz, brabant and twn. So I guess this tool is still under B&O  @lexvand ?

======================================
Noticed while working on the ticket:

**Staging**
Currently, staging on the rain report app keeps redirecting, which makes staging quite unusable.
https://nxt3.staging.lizard.net/report/rain/

The branch is updated and the redirect is commented out. This might also (temporarily) solve the issue on staging, though you would need the login, otherwise the raster aggregates api calls will not work (whether it is about api v2 or api v3).
We need the redirect for production, so we must make sure that the redirect part is uncommented when putting it to staging.

**Development**
Currently, on development (without redirect), most of the app is working (no crash and the wms layers are shown).
The raster aggregates api call however becomes a 404 error, because the user is not logged in.
NOTE: at any point in the future, we can perhaps also add authorization in a development config file in which the developers can (temporarily and locally) add theur credentials? No sending to and updating master with it.

======================================
To do:

**SSH key** (GitHub)
- [x] For me (Madeleine), it is currently not possible to deploy the rain report to staging, because I cannot find my SSH key to be put in de deploy/auth.json (in the rain_report repo). For this, I will 
* generate a new SSH key:
https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
* and I will add it to GitHub:
https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account
https://github.com/settings/ssh/new
- [x] Also make a backup of the key, so I can in the future use it for the lizard-client, and I don't have to keep creating new keys. :)
- [ ] ~~Get/ Generate SSH auth token~~ No longer necessary
- [x] Back up the staging app/config.json file again to see whether anything has changed since the previous pull from staging, if so, create a new staging release.
- [x] Run the deploy script for v1.6.32 (unless something in the staging config.json has changed, than use the new release.
If this does not work because there still seems to be an authentication issue, check whether you can:
* ssh to the server
* ssh-copy-id to the server
- [ ] ~~Because the SSH key is new, a provisioning for staging may also be needed, if the ansible deploy to staging still does not work. Ask Carsten to help out with this. Though probably this is not necessary, because the provisioning is linked to the GitHub account, and not to the ssh key.
If this step was not necessary, also stripe through the part that a provisioning might be needed in the Production part below.~~
- [ ] ~~If provisioning needs to be run for staging again (above step), than it will probably also be needed for production.~~
- [x] In order to make me (Madeleine) able to deploy to staging again, my public key has been added to the .ssh/authorized_keys of buildout on the staging web server s-web-ws-d10.
- [x] The above has also been done for all the production web servers d24-d28, so that I (Madeleine) can also deploy to production again with the new computer.

**Staging**
- [x] See the tutorial about backupping the configuration file from the server before doing anything with staging
- [x] Putting the current branch to staging with the redirect to test the branch on staging. Because staging is broken, it may not work with redirect (because you keep getting redirected).
- [ ] ~~Putting the current branch to staging without the redirect to test the branch on staging. Because staging is broken, it may not work without redirect (because you need a login to get to the raster aggregates data).~~
- [x] Test on staging to see if it it works, if not: (see comments) --> currently, it still doesn't work on staging
- [x] Make a new staging release with the proper rainRasterStoreUUID in the app/config.json and the app/templates/config.json.staging: 3e5f56a7-b16e-4deb-8449-cc2c88805159
(The rainRasterStoreUUID in the app/config.json for production is 730d6675)
* Get the config from staging and see if anything has changed since the last time.
`scp your_username@<staging_server>:/srv/nxt3.staging.lizard.net-clients/rain_report/config.json /home/tomdeboer/dev/rain_report/app/templates/config.json.staging`
or
`scp your_username@<staging_server>:/srv/nxt3.staging.lizard.net-clients/rain_report/config.json /home/madeleine/code/rain_report/app/templates/config.json.staging`
* Make sure that the mapbox urls are also the right ones in the app/config.json and the app/templates/config.json.staging.
* Make sure that everywhere the v2 are changed into v3, also the ones in the app/config.json and the app/templates/config.json.staging.
* Make sure that the redirect is there
* Also mention in the GitHub releases that it's about a prerelease and mention staging in the name of the release!
This release was the **1.6.45 release**:
https://github.com/nens/rain_report/releases/tag/v1.6.45
- [x] Test it again on staging
The good thing with the previous staging release (v1.6.45):
The api that are set from v2 to v3 work. (This might also be the reason why staging is no longer reloading the entire page anymore.)
* But staging hangs on the welcome screen. **This apparently is the same bug that is and was already on production.**
**The errors are mentioned in the ticket about staging/ production:**
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/rain_report/30
** Also the report part of the start screen is not properly outlined on staging. This may need to be solved before going to production.*
https://nxt3.staging.lizard.net/report/rain/
- [ ] Make a new staging release with the redirect commented out. This may not work, because you probably need authentication for loading the rasters. ~~You could however add auth manually on the server, like how it is done for dev. But this is really unrecommended.~~
~~**Don't forget to remove this!**~~
- [ ] Test it again on staging.
- [ ] If all staging options fail and it seems impossible to test it on staging with the current state of staging, tell a PM (Joeri still is on a holiday today, so Lex might know who to contact) about it, before moving to production. Currently Joeri is discussing this with Lex.

**Production + rollback**
- [ ] Before doing anything, check the version of the rain report on production
Current version of rain report on production is: ...?
Check whether this is also the same version as mentioned on GitHub to be the production release. If not, update GitHub.
- [ ] See the tutorial about backupping the configuration file from the server before doing anything with production and back up the app/config.json from the production server.
`Production: scp your_username@<staging_server>:/srv/nxt.lizard.net-clients/rain_report/config.json /home/tomdeboer/dev/rain_report/app/templates/config.json.prod`
or
`Production: scp your_username@<staging_server>:/srv/nxt.lizard.net-clients/rain_report/config.json /home/madeleine/code/rain_report/app/templates/config.json.prod`
- [ ] Check whether the backed up app/config.json from production if the same as from the release you want to put on production. If this is not the case, create a new release with the newly backed up config.json.
If this option is used, the release is: ...
**So that you can allways rollback to the current state of production, with the proper release and the proper app/config.json**
- [ ] Create the new release that is meant to be put on production. Make sure that:
* it has v2 changed into v3 (also in the app/config.json!)
* it has the proper rainRasterStoreUUID in the app/config.json for production: 730d6675
* the redirect is not commented out
* it has the proper mapbox urls in the app/config.json
**If you follow this order, than the order of the releases on GitHub will also be a proper chronological representation of the release state of the repo.**
- [ ] Do the deploy together with Tom
For Madeleine's deploy:
* First check whether you can ssh to the server (this is probably already done in the step where you check the version of the rain_report on production)
If the deploy does not work because there still seems to be an authentication issue, check whether you can:
* ssh to the server
* ssh-copy-id to the server
Because the SSH key is new, a provisioning for production may also be needed (probably the same case as for staging), if the ansible deploy to production does not work. Ask Carsten to help out with this.
- [ ] Test on production (also ask advisor)
- [ ] Rollback to a previous version if it does not work
- [ ] Mail PM (Joeri still is on a holiday today, so Lex might know who to contact)/ Lex about outcome

**Tickets + readme**
- [ ] Update readme with point about commenting out redirect (for local development)
See https://github.com/nens/rain_report/pull/29/commits/b64c9ac17d825c248051b517a6c7e235d7146ca8
- [x] Make a new ticket for fixing the staging and production environment for the rain report to a workable staging. (probably has low priority)
--> https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/rain_report/30
- [ ] Update readme with that you need a deploy/auth.json before you run `npm run buck-trap` --> see github of lizard-client about how to add this
https://github.com/nens/lizard-client#release
- [ ] Update readme with that .external-nens.local should be part of server name? (or make it a bit broader to explain the context and saying that you need the complete server name ..)
- [ ] Update readme: in the readme there is a small part about the rainRasterStoreUUID, and the rainRasterStoreUUID for staging is mentioned.
It would also be nice to mention the rainRasterStoreUUID for production. In case you need to switch the rainRasterStoreUUID to staging, then you can also easily find back what the rainRasterStoreUUID is for production if it is mentioned in the same place
- [ ] Update readme with that you need to `nvm use 8.17.0`, if I hadn't already put that in the readme. This rain_report needs an older version of node, just like the lizard-client, in comparison with for example the 3Di live site and the management screen.

Pull request:
https://github.com/nens/rain_report/pull/29

**Comment by GeOdin** [comment]
Duplicate ticket: https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-client/1116

Idea from Lex: skip api v3 (if possible) and upgrade the api calls from api v2 to api v4.

**Comment by GeOdin** [comment]
There was another ticket about the rain report, in which I also made a few comments.
https://app.zenhub.com/workspaces/team-frontend-5ede33ae05991b2798f63255/issues/nens/lizard-client/1116

@lexvand 
In the ticket mentioned before, the kpi dashboard is also mentioned as possibly needing updates from api v2 to api v3 (if that is in the B&O contract).
https://github.com/nens/kpi-dashboard/issues/54
Should we also make a ticket for that? I saw that the backend commented in that issue, but that there was no conclusion or ticket made out of it.

**Comment by GeOdin** [comment]
Copied from previous ticket:

There were some troubles with starting up the rain_report repo.
Downgrading node to v8.17.0 with nvm (same version as currently used for lizard-client) solved this problem.
I updated the readme:
https://github.com/nens/rain_report/commit/da3f21004abb10501211deb8438cf93ec8be3019

Even with adding the password for authorization in the webpack-dev-server.js, you still get a redirect to demo.lizard.net.
I will try to see if I can get past this redirect on Monday. (localize and temporarly shutting it down)

Further to do:

- change api calls from api v2 to v3
- it may be necessary to test on staging because it may not be possible to test on dev
- STAGING -> download and save config file from server!!!!! before you get started with staging (see readme)
- ask advisor (Ivar?) to test it
- PRODUCTION -> together with Tom
- also download and save config file from server!!!!! before you get started with staging (see readme)

**Comment by GeOdin** [comment]
Note: the current version of rain_report on GitHub (before this branch) was v1.6.29

The current version of rain_report on the staging Lizard server (before this branch) was v1.6.27

**Comment by GeOdin** [comment]
@Derryrover Could you review the branch?

The current branch is in the staging phase.
Before merging it with master, "rainRasterStoreUUID" should be updated in app/config.json to become:
"rainRasterStoreUUID":"730d6675",

See
https://github.com/nens/rain_report/pull/29/commits/fac4eb9e6e9e780edc4fc68174337025f1ffad7e

Edit: in the meantime, I will update the readme and make another ticket for a staging bug (though perhaps it may be solved with this branch).
I will also make a new SSH key to see if that can help me with deploying to staging.

**Comment by Derryrover** [comment]
@GeOdin 

Hi Madeleine 
I have the following thoughts about going to production.
kr Tom


Currently we are updating rain report from apiv2 to apiv3
We have some trouble testing here:
https://nxt3.staging.lizard.net/report/rain/
We keep getting redirected. (are there other problems? can we temporarily turn of the redirect?)

I see 2 options:
- We find someway to do test on staging
- We deploy to production without testing while communicating this clear to PM's and we will have a rollback release right ready
(this rollback release needs to have the latest version of the config file ! , we can thus maybe not use the old release, but need to make a new one)

**Comment by GeOdin** [comment]
Hey @Derryrover 

I agree and have previously mentioned the following:

**Staging is not working properly.**
* With redirect, it might not work, because staging is broken
* Without redirect, it might not work, because you would need to log in to see the api calls

Possible solutions:
* updating the config files of staging with the new api version, new mapbox url (which was apperently still the old mapbox url on staging) and update the rainRasterStoreUUID of the app/config.json to the staging one -> will I think not fix the problem we cannot test
* We could however put it on staging and add one of our authentication manually on staging and removing it later on (what we also do for dev) -> Is probably very unsecure. Lete us not do it
* We could also try to solve staging problems first if the above 2 possible solutions are not sufficient.

Depending on what we choose, we should also update Lex, I think.

What do you think?

**Comment by GeOdin** [comment]
I seem to run into another issue with buck-trap that prevents me from creating a release and putting it on GitHub, when running
`npm run buck-trap`

The error when I show the log file:
$ more /home/madeleine/.npm/_logs/2020-08-31T09_41_25_503Z-debug.log

@Derryrover 
Do you have an idea how I could solve this?
In the meanwhile, I will try to have a look at the buck-trap script.

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/home/madeleine/.nvm/versions/node/v8.17.0/bin/node',
> 1 verbose cli   '/home/madeleine/.nvm/versions/node/v8.17.0/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'buck-trap' ]
> 2 info using npm@6.13.4
> 3 info using node@v8.17.0
> 4 verbose run-script [ 'prebuck-trap', 'buck-trap', 'postbuck-trap' ]
> 5 info lifecycle rain_report@1.6.36~prebuck-trap: rain_report@1.6.36
> 6 info lifecycle rain_report@1.6.36~buck-trap: rain_report@1.6.36
> 7 verbose lifecycle rain_report@1.6.36~buck-trap: unsafe-perm in lifecycle true
> 8 verbose lifecycle rain_report@1.6.36~buck-trap: PATH: /home/madeleine/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/madeleine/code/rain_report/node_modul
> es/.bin:/home/madeleine/.nvm/versions/node/v8.17.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> 9 verbose lifecycle rain_report@1.6.36~buck-trap: CWD: /home/madeleine/code/rain_report
> 10 silly lifecycle rain_report@1.6.36~buck-trap: Args: [ '-c', 'buck-trap -a' ]
> 11 silly lifecycle rain_report@1.6.36~buck-trap: Returned: code: 1  signal: null
> 12 info lifecycle rain_report@1.6.36~buck-trap: Failed to exec buck-trap script
> 13 verbose stack Error: rain_report@1.6.36 buck-trap: `buck-trap -a`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/home/madeleine/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at EventEmitter.emit (events.js:214:7)
> 13 verbose stack     at ChildProcess.<anonymous> (/home/madeleine/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at ChildProcess.emit (events.js:214:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:915:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid rain_report@1.6.36
> 15 verbose cwd /home/madeleine/code/rain_report
> 16 verbose Linux 5.4.0-42-generic
> 17 verbose argv "/home/madeleine/.nvm/versions/node/v8.17.0/bin/node" "/home/madeleine/.nvm/versions/node/v8.17.0/bin/npm" "run" "buck-trap"
> 18 verbose node v8.17.0
> 19 verbose npm  v6.13.4
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error rain_report@1.6.36 buck-trap: `buck-trap -a`
> 22 error Exit status 1
> 23 error Failed at the rain_report@1.6.36 buck-trap script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
>

**Comment by GeOdin** [comment]
Note:
Released v1.6.45 this morning on staging.

The redirect problem is over.
This might be due to the fact that the app/config.json (and the app/templates/config.json.staging) is now the right staging rainRasterStoreUuid.

Staging does hang on the welcome modal.
After checking production, apparently this is and was already the case on production.

@Derryrover 
Extra note for the staging release v1.6.45:
When scrolling down, the graphs are not outlined properly.
https://nxt3.staging.lizard.net/report/rain/

**Comment by Derryrover** [comment]
@lexvand 

Hi Lex,

I found a way to test it on staging.
Please have a look here:
https://nxt3.staging.lizard.net/report/rain/

I think it all works well. If you agree we can deploy to production.

kr Tom

**Comment by lexvand** [comment]
Looks good. Move on to production.

**Comment by Derryrover** [comment]
Deployed to prod
