### ISSUE TITLE
Production and staging hang on welcome screen

### ISSUE THREAD

**Issue by GeOdin** [nens/rain_report#30]
Production and staging for rain report hangs on the welcome screen.

The previous error of refreshing on staging has been dealt with, probably because with the v1.6.45 release of the rain_report, the right rainRasterStoreUuid has been used for the app/config.json (and app/templates/config.json.staging).
https://github.com/nens/rain_report/releases/tag/v1.6.45

But a new issue arised, namely that production and staging now hangs on the welcome screen.

Error message in the console:

> TypeError: s.querySelector(...) is null
>     h https://nxt3.staging.lizard.net/report/rain/app.js:35
>     $digest https://nxt3.staging.lizard.net/report/rain/app.js:53
>     $apply https://nxt3.staging.lizard.net/report/rain/app.js:53
>     a https://nxt3.staging.lizard.net/report/rain/app.js:52
>     v https://nxt3.staging.lizard.net/report/rain/app.js:52
>     onload https://nxt3.staging.lizard.net/report/rain/app.js:52

It could also be the favicon, which gives a 404 error [HTTP/2 404 Not Found 77ms]:
GEThttps://nxt3.staging.lizard.net/images/favicon.png

Staging url:
https://nxt3.staging.lizard.net/report/rain/

Production url:
https://demo.lizard.net/report/rain/

Note: this same problem is an issue on production as well as staging.

**Comment by GeOdin** [comment]
@lexvand 

Hey Lex,

I saw that I had not tagged you before.

This is a known issue.

Kind regards,
Madeleine

**Comment by lexvand** [comment]
@GeOdin It does work on for instance https://rotterdam.lizard.net/report/rain. On demo and staging the rain report is not configured. If this answers the question please close the issue.

**Comment by GeOdin** [comment]
@lexvand 

Hey Lex,

That indeed answers the question.

Thank you!
